### ISSUE TITLE
Task List for Milestone 1

### ISSUE THREAD

**Issue by ebeshero** [newtfire/locke-anthology#2]
- [ ] @ZSchleger dresses up the poems list in markdown
- [ ] Create a directory for separate text files maybe named "text" @julianjmg 
- [ ] Create a directory for TEI XML files, maybe "tei" @julianjmg 
- [ ] Prep the ODD file 
- [ ]
